rvm:
 - 1.9.3
 - 2.0.0
 - 2.1
 - 2.2.4
 - 2.3.1
 - ruby-head

gemfile:
 - Gemfile
 - Gemfile.v0.12

services:
  - mongodb

before_install:
  - gem update bundler
before_script:
  - git submodule update -i

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
